spring:
  application:
    name: currency-exchange-rate
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:currency-exchange-rate

application:
  scheduling:
    enabled: true
    interval: 5000
  urls:
    currencyConverterApi: http://free.currencyconverterapi.com/api/v5/convert?q=EUR_USD&compact=y