spring:
  application:
    name: currency-exchange-exchangeRate
  profiles:
    active: dev
  jackson:
    serialization-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
      write_dates_as_timestamps: false
  datasource:
    url: jdbc:h2:mem:currency-exchange-exchangeRate
  h2:
    console:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: threaddump, env, configprops
